FROM base

ARG USER

USER root

RUN wget https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip && \
  unzip terraform_0.12.31_linux_amd64.zip && \
  mv terraform /usr/bin && \
  rm -f terraform_0.12.31_linux_amd64.zip

USER $USER

ENTRYPOINT ["tail", "-f", "/dev/null"]
