FROM base

ARG USER

USER root

RUN apt-get update && apt-get install -y apt-transport-https && \
  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
  echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | \
  tee -a /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update && \
  apt-get install -y kubectl

USER $USER

ENTRYPOINT ["tail", "-f", "/dev/null"]
