FROM base

USER root

RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/ludorl82/.shell-scripts/master/scripts/install_ssh.sh)"

# Install OpenSSH server
RUN mkdir /run/sshd
RUN ssh-keygen -A

CMD ["/usr/sbin/sshd", "-D", "-o", "ListenAddress=0.0.0.0"]
