FROM base

ARG USER

USER root

RUN wget https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip && \
  unzip terraform_1.1.9_linux_amd64.zip && \
  mv terraform /usr/bin && \
  rm -f terraform_1.1.9_linux_amd64.zip

USER $USER

ENTRYPOINT ["tail", "-f", "/dev/null"]
